name: PullReqeust Comment bot

on:
  issue_comment:
    types: [created]

jobs:
  check_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: MeilCli/commenter@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trigger_regex: レビュー開始
          assign_reviewers: MeilCli,MeilCli-bot
          assign_labels: documentation
